tag-prefix = "v"
no-dev-version = true
disable-push = true
pre-release-commit-message = "(cargo-release) bump version to {{version}}"

[[pre-release-replacements]]
file = "README.md"
search = "https://deps.rs/crate/finchers-r2d2/[a-z0-9\\.-]+"
replace = "https://deps.rs/crate/finchers-r2d2/{{version}}"

[[pre-release-replacements]]
file = "src/lib.rs"
search = "https://docs.rs/finchers-r2d2/[a-z0-9\\.-]+"
replace = "https://docs.rs/finchers-r2d2/{{version}}"
